### ISSUE TITLE
AppVeyor error

### ISSUE THREAD

**Issue by wasd171** [YellowKirby/is-ci-cli#4]
Hi!

AppVeyor fails (`1.1.1`) with following:
```
> chatinder@1.4.5 postinstall C:\projects\chatinder
> is-ci 'ci:skip' 'install:types'
npm ERR! missing script: 'ci:skip'
```

OS X build works

**Comment by wasd171** [comment]
Removing quotes from the command (`is-ci ci:skip install:types`) has fixed it, but I believe the README should be updated

**Comment by YellowKirby** [comment]
Ha, silly Windows. Thank you for reporting! I've updated the README to no longer use any quotes. FWIW, if somebody _really needs_ a quoted script name, using `\"escaped double quotes\"` should work.
